### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'isolated_build_env'

### ISSUE THREAD

**Issue by bastienboutonnet** [enpaul/tox-poetry-installer#35]
I'm getting the following error when calling `tox`:

```bash
➜ tox
.tox create: /Users/bboutonnet@tripactions.com/Documents/repos/sheetwork/.tox/.tox
Traceback (most recent call last):
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox/session/__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox/session/__init__.py", line 187, in runcommand
    return provision_tox(provision_tox_venv, self.config.args)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox/session/commands/provision.py", line 10, in provision_tox
    ensure_meta_env_up_to_date(provision_venv)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox/session/commands/provision.py", line 24, in ensure_meta_env_up_to_date
    if provision_venv.setupenv():
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox/venv.py", line 628, in setupenv
    status = self.update(action=action)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox/venv.py", line 275, in update
    self.hook.tox_testenv_install_deps(action=action, venv=self)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox_poetry_installer/hooks.py", line 73, in tox_testenv_install_deps
    poetry = utilities.check_preconditions(venv, action)
  File "/Users/bboutonnet@tripactions.com/Library/Caches/pypoetry/virtualenvs/sheetwork-H1mpejJG-py3.8/lib/python3.8/site-packages/tox_poetry_installer/utilities.py", line 139, in check_preconditions
    if action.name == venv.envconfig.config.isolated_build_env:
AttributeError: 'Config' object has no attribute 'isolated_build_env'
```

my tox config looks like this:
```ini
[tox]
envlist = {py3611,py37,py38}-{cover,nocov}-{linux,windows}
isolated_build=true
requires =
    tox-poetry-dev-dependencies
    tox-wheel

[gh-actions]
python =
    3.8: py38
    3.6: py3611
    3.7: py37

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    windows-latest: windows

[testenv]
poetry_experimental_add_locked_dependencies = True
poetry_add_dev_dependencies = True
wheel =
    cover: false
    nocover: true
setenv =
    APPDATA = "''"
whitelist_externals = echo
commands =
    echo {env:APPDATA}
    pytest

[testenv:package]
skip_install = True
deps =
    twine
commands =
    python3 -m poetry build
    python3 -m twine check dist/*
```

Am I potentially doing something bad in my config? I tried looking for similar error messages but couldn't find anything with `isolated_build_env` in there.

**Comment by enpaul** [comment]
@bastienboutonnet Thanks for reporting this error! Could you share what version of tox and what version of the plugin you're using?

**Comment by bastienboutonnet** [comment]
Thanks for the quick reply @enpaul and yes of course I can. Stupid of me not to have done so before...
```bash
tox                        3.21.0
tox-poetry-installer       0.6.1
```

I managed to get it working a week or so ago, but I can't recall if I upgraded some packages in the meantime or no. Could have been the case.

**Comment by enpaul** [comment]
@bastienboutonnet Thank you! I notice you're using tox 3.21 there, which was just released a few days ago. I haven't had a chance to test the plugin with 3.21 yet so I'm not sure if it works properly. If it doesn't then it's possible there's a bug in tox itself, but I'm not sure. I should be able to take a look at reproducing this bug either tomorrow or Monday evening, but my first instinct would be to suggest downgrading to tox 3.20 and see if the problem persists.

**Comment by bastienboutonnet** [comment]
Hi again @enpaul downgrading to `3.20.0` did the trick so it looks like somewhere between 3.20 and 3.21 something might have "broken".

I'll keep watching this issue as I'm curious to know when I might be able to use the latest version of tox (not that I need anything in 3.21 but I like to stay up to date with most packages).

**Comment by enpaul** [comment]
Taking a closer look at this, I'm actually not convinced this is a problem with `3.21.x`. I was just able to repro it on `3.20.1`. I think the problem is actually related to the usage of the Tox `requires` option. I believe the `.tox` environment (the provisioned env Tox creates for itself when using either `requires` or `minversion`) does not populate the `isolated_build_env` setting in its config. I think the solution is add another precondition to check for whether the current env is the [`provision_tox_env`](https://tox.readthedocs.io/en/latest/config.html#conf-provision_tox_env) before checking for `isolated_build_env`.

**Comment by enpaul** [comment]
@bastienboutonnet Thanks for your patience while I got this figured out! The recent `tox-poetry-installer 0.6.2` update should fix this problem. When you get a chance could you try updating and see if that fixes the issue?

**Comment by bastienboutonnet** [comment]
Hi @enpaul thanks a lot for following up! I upgraded both tox and tox-poetry-installer and it all seems to work 🥳
